image: registry.splentity.com/openblox/ci-build-environment/ob:latest

build:
  script:
    - ./autoconf.sh
    - ./configure
    - make
  
pages:
  script:
    - doxygen Doxyfile
    - mv docs/html public
  artifacts:
    paths:
      - public
  only:
    - master
