image: registry.splentity.com/openblox/ci-build-environment/ob:latest

build:
  artifacts:
    paths:
      - artifacts
  script:
    - ./autoconf.sh
    - mkdir artifacts
    - ./configure --prefix=$(readlink -f artifacts)
    - make
    - make install
    - cp libopenblox.pc artifacts
  
pages:
  script:
    - doxygen Doxyfile
    - mv docs/html public
  artifacts:
    paths:
      - public
  only:
    - master
