image: johnmh/ob-env

build:
  script:
    - ./autoconf.sh
    - ./configure
    - make
  
pages:
  script:
    - doxygen Doxyfile
    - mv docs/html public
  artifacts:
    paths:
      - public
  only:
    - master
